-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('GENERAL', 'ACHIEVEMENT', 'REMINDER', 'COMMUNITY', 'LIKE', 'COMMENT', 'FOLLOW', 'SYSTEM', 'TEST', 'AFFIRMATION', 'ANNOUNCEMENT') NOT NULL DEFAULT 'GENERAL';
